[package]
name = "cargo-shallguard"
version = "0.1.1"
authors = ["Tomas Siegl <tomas.siegl@gmail.com>"]
edition = "2024"
rust-version = "1.89"
publish = ["crates-io"]
description = "Cargo subcommand for ShallGuard requirement assurance"
license = "MIT"
repository = "https://github.com/sigi64/shallguard"
documentation = "https://docs.rs/cargo-shallguard"
readme = "README.md"
keywords = ["shallguard", "requirements", "traceability", "cargo", "ci"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
include = ["src/**", "LICENSE", "README.md"]

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]

[[bin]]
name = "cargo-shallguard"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
shallguard = { path = "..", version = "0.1.1" }

[dev-dependencies]
tempfile = "3.23.0"
